config/routes.rb
Rails.application.routes.draw do
  root 'directory_trees#index'

  resources :directory_trees do
    resources :nodes, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/directory_tree.rb
class DirectoryTree < ApplicationRecord
  has_many :nodes
end

app/models/node.rb
class Node < ApplicationRecord
  belongs_to :directory_tree
  belongs_to :parent, class_name: 'Node', required: false
  has_many :children, class_name: 'Node', foreign_key: 'parent_id'

  scope :roots, -> { where(parent_id: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directory_trees_controller.rb
class DirectoryTreesController < ApplicationController
  before_action :set_directory_tree, only: [:show, :edit, :update, :destroy]

  def index
    @directory_trees = DirectoryTree.all
  end

  def show; end

  def new
    @directory_tree = DirectoryTree.new
  end

  def edit; end

  def create
    @directory_tree = DirectoryTree.new(directory_tree_params)

    if @directory_tree.save
      redirect_to directory_trees_url,
                  notice: 'Directory tree was successfully created.'
    else
      render :new
    end
  end

  def update
    if @directory_tree.update(directory_tree_params)
      redirect_to directory_trees_url,
                  notice: 'Directory tree was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @directory_tree.destroy
    redirect_to directory_trees_url,
                notice: 'Directory tree was successfully destroyed.'
  end

  private

  def set_directory_tree
    @directory_tree = DirectoryTree.find(params[:id])
  end

  def directory_tree_params
    params.require(:directory_tree).permit(:name)
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def new
    @node = Node.new
  end

  def create
    @directory_tree = DirectoryTree.find(params[:directory_tree_id])
    @node = @directory_tree.nodes.build(node_params)

    @node.save
    redirect_to directory_tree_path(params[:directory_tree_id]),
                notice: 'Node was successfully created.'
  end

  private

  def node_params
    params.require(:node).permit(:name, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directory_trees/_create_new_node.html.erb
<div class='new-node-form'>
  <%= form_with url: directory_tree_nodes_path(directory_tree_id), local: true do |f| %>
    |-- [ <%= f.text_field 'node[name]' %> ]
    <%= f.hidden_field 'node[parent_id]', value: parent_id %>

    <%= f.submit "ADD NEW NODE", :class => 'btn btn-light' %>
  <% end %>
</div>

app/views/directory_trees/_form.html.erb
<%= form_with(model: directory_tree, local: true) do |form| %>
  <% if directory_tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(directory_tree.errors.count, "error") %> prohibited this directory_tree from being saved:</h2>

      <ul>
      <% directory_tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/directory_trees/_node_data.html.erb
<p>|-- <%= node.name %></p>

<% unless node.children.present? %>
  <div class='add-new-node-block'>
    <%= render 'create_new_node', directory_tree_id: directory_tree_id, parent_id: node.id %>
  </div>
<% end %>

<% node.children.each_with_index do |child, i| %>
  <div class='children-nodes'>
    <%= render 'node_data', node: child, directory_tree_id: directory_tree_id %>

    <% if i+1 == node.children.count %>
      <%= render 'create_new_node', directory_tree_id: directory_tree_id, parent_id: node.id %>
    <% end %>
  </div>
<% end %>

app/views/directory_trees/edit.html.erb
<h1>Editing Directory Tree</h1>

<%= render 'form', directory_tree: @directory_tree %>

</br>

<%= link_to 'Show', @directory_tree, :class => 'btn btn-primary' %>
<%= link_to 'Back', directory_trees_path, :class => 'btn btn-primary' %>

app/views/directory_trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='title'>Directory Trees</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @directory_trees.each do |directory_tree| %>
      <tr>
        <td><%= link_to directory_tree.name, directory_tree %></td>
        <td><%= link_to 'Edit Name', edit_directory_tree_path(directory_tree),
                :class => 'btn btn-success' %></td>
        <td><%= link_to 'Destroy', directory_tree,
                method: :delete,
                data: { confirm: 'Are you sure?' },
                :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directory Tree', new_directory_tree_path, :class => 'btn btn-primary' %>

app/views/directory_trees/new.html.erb
<h1>New Directory Tree</h1>

<%= render 'form', directory_tree: @directory_tree %>

</br>

<%= link_to 'Back', directory_trees_path, :class => 'btn btn-primary' %>

app/views/directory_trees/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class='title'><%= @directory_tree.name %></h1>

<% @directory_tree.nodes.roots.each do |root| %>
  <%= render 'node_data', node: root, directory_tree_id: @directory_tree.id %>
<% end %>

<%= render 'create_new_node', directory_tree_id: @directory_tree.id, parent_id: nil %>

</br>

<%= link_to 'Edit', edit_directory_tree_path(@directory_tree), :class => 'btn btn-primary' %>
<%= link_to 'Back', directory_trees_path, :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lumostree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <div class='container'>
        <%= yield %>
    </div>

  </body>
</html>